[buildPlans.RicoCode]
exportGlyphNames = false
family = "Rico Code"
noCvSs = true
serifs = "sans"
spacing = "normal"

[buildPlans.RicoCode.variants]
inherits = "ss06"

[buildPlans.RicoCode.variants.design]
asterisk = "penta-low"
at = "compact"
capital-g = "toothed-serifless-hookless"
capital-j = "serifless"
capital-q = "crossing"
diacritic-dot = "round"
five = "upright-arched-serifless"
j = "serifless"
lig-ltgteq = "slanted"
punctuation-dot = "round"
tittle = "round"
two = "straight-neck-serifless"

[buildPlans.RicoCode.ligations]
inherits = "javascript"

[buildPlans.RicoCode.weights.Regular]
css = 400
menu = 400
shape = 400

[buildPlans.RicoCode.weights.Bold]
css = 700
menu = 700
shape = 700

[buildPlans.RicoCode.slopes.Upright]
angle = 0
css = "normal"
menu = "upright"
shape = "upright"

[buildPlans.RicoCode.slopes.Italic]
angle = 9.4
css = "italic"
menu = "italic"
shape = "italic"
